stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  CYPRESS_RECORD_KEY: $CYPRESS_RECORD_KEY
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

install dependencies:
  image : cypress/browsers
  stage: build
  script:
    - npm ci 
    - npm install mochawesome 

unit-test-job:
  image : cypress/browsers
  stage: test
  parallel: 5
  script:
    - npm start &
    - npx cypress run --record --parallel --reporter mochawesome --reporter-options reportDir=mochawesome-report # run the tests
  artifacts:
    when: always
    paths:
      - mochawesome-report/
      - cypress/screenshots/**/*.png
      - cypress/videos/**/*.mp4
    expire_in : 30 days

lint-test-job:   
  stage: test    
  script:
    - echo "Linting code... This will take about 10 seconds."
    - echo "No lint issues found."

deploy-job:      
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
