name: Three Environments Jobs Setup
on: [push]

jobs:

  DevEnvironmentRunning :
    runs-on: windows-latest
    environment: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run : |
          echo "Running Dev Environment"

  TestSuiteRunning:
    runs-on: windows-latest
    environment: QA
    needs: DevEnvironmentRunning
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0

  Production:
    runs-on: windows-latest
    environment: PROD
    needs: TestSuiteRunning
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Deploy to Production
        run: |
          echo "Deploying to Production"